/**
   \file llvm/tiger-runtime.c
   \brief C Implementation of the Tiger runtime.
*/

#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define EXIT_RUNTIME_FAILURE 120

// FWD, declared by tc
void tc_main(int);


/// Functions are marked with `__attribute__((weak))` so they
/// can be overriden when the gc runtime is linked.
__attribute__((weak)) void gc_enter_runtime(
)
{}
__attribute__((weak)) void gc_exit_runtime(
)
{}



/** \name Internal functions (calls generated by the compiler only). */
/** \{ */

/** \brief Allocate size bytes of memory and fill them with zeros.
    \param size    The number of bytes to allocate.
*/
__attribute__((weak)) void* tc_malloc(size_t size)
{
  void* a = malloc(size);
  if (a == NULL)
    {
      static const char msg[] = "malloc: memory exhausted\n";
      fwrite(msg, 1, sizeof(msg) - 1, stderr);
      exit(EXIT_RUNTIME_FAILURE);
    }

  memset(a, 0, size);
  return a;
}

/** \brief Allocate an array and fill it with a default value.
    \param size    The size of the array.
    \param elt     The default element.

    An element size is the size of a word.
*/
__attribute__((weak)) int64_t* tc_init_array(int64_t size, int64_t elt)
{
  int64_t* arr = (int64_t*)tc_malloc(size * sizeof(elt));
  for (size_t i = 0; i < size; ++i)
    arr[i] = elt;
  return arr;
}

/** \brief Allocate an array and fill it with a default value.
    \param size    The size of the array.
    \param elt     The default element.
*/
__attribute__((weak)) int64_t* tc_init_ptr_array(int64_t size, int64_t elt)
{
  return tc_init_array(size, elt);
}
/** \} */

/** \name Miscellaneous */
/** \{ */

/** \brief Allocate a string and fill it zeros.
    \param size    The size of the string in bytes.
*/
__attribute__((weak)) char* tc_init_string(size_t size)
{
  return (char*)tc_malloc(size);
}
/** \} */

/** \brief Equivalent to operator! in C.
    \param i       The integer to be inversed.
*/
int64_t tc_not(int64_t i) { return !i; }

/** \brief Exit the program with the desired status.
    \param status  The status code.
*/
void tc_exit(int64_t status) { exit(status); }
/** \} */

/** \name Operations on strings. */
/** \{ */

// Small trick. Add a \0 after each char in the consts
// This is filled in tc_main
static char consts[512] = {0};

/** \brief Get a string containing the character represented by the ascii value
 *         of \a i.
    \param i  The ascii value of the desired character.
*/
const char* tc_chr(int64_t i)
{
  if (!(0 <= i && i <= 255))
    {
      fputs("chr: character out of range\n", stderr);
      exit(EXIT_RUNTIME_FAILURE);
    }
  return consts + i * 2;
}

/** \brief Concatenate two strings.
    \param a  The first string.
    \param b  The second string.
*/
const char* tc_concat(const char* a, const char* b)
{
  size_t len_a = strlen(a);
  size_t len_b = strlen(b);
  if (len_a == 0)
    return b;
  else if (len_b == 0)
    return a;
  else
    {
      size_t i = 0;
      size_t n = len_a + len_b;
      char* t = tc_init_string(n + 1);
      for (i = 0; i < len_a; i++)
        t[i] = a[i];
      for (i = 0; i < len_b; i++)
        t[i + len_a] = b[i];
      t[n] = '\0';
      return t;
    }
}

/** \brief Get the ascii value of a character.
    \param s  The string representing the desired character to be converted.

    Inverse of `tc_chr`.
*/
int64_t tc_ord(const char* s)
{
  size_t len = strlen(s);
  if (len == 0)
    return -1;
  else
    return s[0];
}

/** \brief Get the size of a string.
    \param s  The string.
*/
int64_t tc_size(const char* s) { return strlen(s); }

/** \brief Return a part of the string \a s.
    \param s       The source string
    \param first   The first character of the extraction (starting at 0)
    \param n       The number of characters to get.

    \a first and \a n must be positive, and one shall not go beyond the size
    of \a s.  Otherwise, exit with runtime failure.
*/
const char* tc_substring(const char* s, int64_t first, int64_t n)
{
  size_t len = strlen(s);
  if (!(0 <= first && 0 <= n && first + n <= len))
    {
      fputs("substring: arguments out of bounds\n", stderr);
      exit(EXIT_RUNTIME_FAILURE);
    }

  if (n == 1)
    return consts + s[first] * 2;
  else
    {
      char* t = (char*)tc_init_string(n + 1);
      for (int i = 0; i < n; i++)
        t[i] = s[first + i];
      t[n] = '\0';
      return t;
    }
}

/** \brief Compare two strings.
    \param lhs       The first string.
    \param rhs       The second string.
*/
int64_t tc_strcmp(const char* lhs, const char* rhs) { return strcmp(lhs, rhs); }

/** \brief Return a part of the string \a s.
    \param s       The source string
    \param first   The first character of the extraction (starting at 0)
    \param n       The number of characters to get.

    \a first and \a n must be positive, and one shall not go beyond the size
    of \a s.  Otherwise, exit with runtime failure.
*/
int64_t tc_streq(const char* lhs, const char* rhs)
{
  return strcmp(lhs, rhs) == 0;
}
/** \} */

/** \name Input/Output. */
/** \{ */

/** \brief Get a character from the standard input.
 */
const char* tc_getchar()
{
  int i = getc(stdin);
  if (i == EOF)
    return "";
  else
    return consts + i * 2;
}

/** \brief Print a string on the standard output.
    \param s   The string to be printed.
*/
void tc_print(const char* s) { printf("%s", s); }

/** \brief Print a string on the standard error.
    \param s   The string to be printed.
*/
void tc_print_err(const char* s) { fprintf(stderr, "%s", s); }

/** \brief Print an int on the standard error.
    \param i   The int to be printed.
*/
void tc_print_int(int64_t i) { printf("%" PRId64, i); }

/** \brief Flush the standard output.
 */
void tc_flush() { fflush(stdout); }

void init_consts(void)
{
  // Fill the `consts` array with every character in the ascii table, followed
  // by a null character.
  for (int i = 0; i < 512; i += 2)
    {
      consts[i] = i / 2;
      consts[i + 1] = 0;
    }
}

/** \} */
__attribute__((weak)) int main()
{
  init_consts();
  tc_main(0);
  return 0;
}
